# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy WebApi

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.8'

      - name: Create and start virtual environment
        run: |
          cd wolflease-webapi
          python -m pip install --upgrade pip
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd wolflease-webapi
          pip install -r requirements.txt
          pip install -U pyopenssl
          python manage.py makemigrations
          python manage.py migrate
          echo "from django.contrib.auth.models import User" > createadmin.py
          echo "User.objects.create_superuser('admin', 'admin@wolflease.com', 'admin')" >> createadmin.py
          python manage.py shell < createadmin.py
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v2
        with:
          name: python-app
          path: |
            wolflease-webapi/
            !wolflease-webapi/venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: python-app
          path: .
          
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'wolflease-api'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_DB6D067C5FEA418A996545C322D6E514 }}
