name: Generate and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_api_job:
    environment:
      name: python-api-docs
      url: ${{ steps.builddeploy.outputs.static_web_app_url }}
    runs-on: ubuntu-latest
    name: Deploy API Docs
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install pdoc3
        run: |
          pip3 install pdoc3
          pip install -r wolflease-webapi/requirements.txt
      - name: Generate Documentation
        run: pdoc --html wolflease-webapi/housing
      - name: Build And Deploy API Documentation
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/html/housing" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######

  build_and_deploy_angular_job:
    environment:
      name: angular-app-docs
      url: ${{ steps.builddeployangular.outputs.static_web_app_url }}
    runs-on: ubuntu-latest
    name: Deploy App Docs
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install compodoc
        run: npm install @compodoc/compodoc
      - name: Generate Documentation
        run: |
          cd wolflease-webapp
          npm run generate-docs
      - name: Build And Deploy APP Documentation
        id: builddeployangular
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_APP_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/wolflease-webapp/documentation" # App source code path
          api_location: "api" # Api source code path - optional
          output_location: "public" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######