name: Run Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        cd wolflease-webapi
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd wolflease-webapi
        coverage run manage.py test housing
    - name: Generate Test Coverage
      run: |
        cd wolflease-webapi
        coverage report
        coverage json
    - name: Generate HTML Pages for Test COverage
      run: |
        cd wolflease-webapi
        coverage html
    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v2
